import { createContext, useContext, useState, useCallback, useEffect, type ReactNode } from "react";

export type Language = "fr" | "en" | "zh" | "ar" | "es" | "pt" | "ja";

export interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
  dir: "ltr" | "rtl";
}

export const languages: LanguageInfo[] = [
  { code: "fr", name: "Français", nativeName: "Français", flag: "🇫🇷", dir: "ltr" },
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧", dir: "ltr" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳", dir: "ltr" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦", dir: "rtl" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸", dir: "ltr" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇧🇷", dir: "ltr" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵", dir: "ltr" },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
  languageInfo: LanguageInfo;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

// ─── Translations ────────────────────────────────────────────────

type Translations = Record<Language, Record<string, string>>;

const translations: Translations = {
  fr: {
    // Navbar
    "nav.home": "Accueil",
    "nav.vpn": "VPN",
    "nav.software": "Logiciels",
    "nav.tools": "Outils",
    "nav.ai": "IA",
    "nav.download": "Télécharger",

    // Hero
    "hero.badge": "Nouveau : Mises à jour quotidiennes",
    "hero.title1": "Vos logiciels préférés",
    "hero.title2": "en un clic",
    "hero.titleHighlight": "préférés",
    "hero.description": "Découvrez et téléchargez les meilleurs VPN, logiciels et outils numériques. Sécurisé, rapide et toujours à jour.",
    "hero.cta1": "Explorer les logiciels",
    "hero.cta2": "Voir les VPN",

    // Features
    "features.speed": "Téléchargement Rapide",
    "features.speedDesc": "Serveurs haute vitesse pour des téléchargements instantanés",
    "features.secure": "100% Sécurisé",
    "features.secureDesc": "Tous les fichiers sont vérifiés et exempts de virus",
    "features.global": "Accès Mondial",
    "features.globalDesc": "Disponible partout dans le monde, 24h/24",

    // Stats
    "stats.downloads": "Téléchargements",
    "stats.users": "Utilisateurs actifs",
    "stats.secure": "Sécurisé",
    "stats.rating": "Note moyenne",

    // VPN Section
    "vpn.badge": "Protection & Confidentialité",
    "vpn.title": "VPN Premium",
    "vpn.seeAll": "Voir tout",
    "vpn.comingSoon": "Plus de VPN bientôt disponibles",
    "vpn.pageTitle": "Les meilleurs VPN pour votre sécurité",
    "vpn.pageDesc": "Protégez votre vie privée en ligne avec notre sélection des VPN les plus fiables et performants du marché.",
    "vpn.allTitle": "Tous les VPN disponibles",
    "vpn.allDesc": "Choisissez le VPN qui correspond à vos besoins",
    "vpn.spaceLabel": "Espace VPN",
    "vpn.spaceReady": "Prêt pour votre contenu",

    // VPN Features
    "vpn.feat.encryption": "Cryptage AES-256",
    "vpn.feat.encryptionDesc": "Protection de niveau militaire pour toutes vos données",
    "vpn.feat.servers": "Serveurs mondiaux",
    "vpn.feat.serversDesc": "Accédez à du contenu de n'importe quel pays",
    "vpn.feat.speed": "Vitesse maximale",
    "vpn.feat.speedDesc": "Aucun ralentissement grâce à nos serveurs optimisés",
    "vpn.feat.logs": "Zéro logs",
    "vpn.feat.logsDesc": "Votre activité en ligne reste totalement privée",
    "vpn.feat.devices": "Multi-appareils",
    "vpn.feat.devicesDesc": "Protégez tous vos appareils simultanément",
    "vpn.feat.killswitch": "Kill Switch",
    "vpn.feat.killswitchDesc": "Protection automatique en cas de déconnexion",

    // Software Section
    "software.badge": "Applications & Programmes",
    "software.title": "Logiciels Populaires",
    "software.pageTitle": "Tous les logiciels",
    "software.pageDesc": "Explorez notre collection complète de logiciels professionnels, utilitaires et outils de productivité.",
    "software.pageBadge": "Bibliothèque de logiciels",
    "software.search": "Rechercher un logiciel...",
    "software.found": "logiciel(s) trouvé(s)",
    "software.spaceLabel": "Espace logiciel",
    "software.spaceReady": "Prêt pour votre contenu",
    "software.reserved": "Espace réservé pour vos logiciels",

    // Categories
    "cat.all": "Tous",
    "cat.system": "Système",
    "cat.video": "Vidéo",
    "cat.security": "Sécurité",
    "cat.utility": "Utilitaires",
    "cat.office": "Bureautique",
    "cat.media": "Multimédia",

    // Videos Section
    "videos.badge": "Tutoriels & Guides",
    "videos.title": "Vidéos & Tutoriels",
    "videos.spaceLabel": "Espace vidéo disponible",

    // Tools Section
    "tools.badge": "Utilitaires & Productivité",
    "tools.title": "Outils Numériques",
    "tools.pageTitle": "Outils numériques",
    "tools.pageDesc": "Des outils essentiels pour diagnostiquer, optimiser et gérer votre système informatique.",
    "tools.allTitle": "Outils disponibles",
    "tools.allDesc": "Téléchargez les outils dont vous avez besoin",
    "tools.comingSoon": "Prochainement disponibles",
    "tools.spaceLabel": "Outil",
    "tools.spaceReady": "Espace disponible",
    "tools.gallery": "Galerie Photos",
    "tools.galleryDesc": "Captures d'écran et aperçus des outils",
    "tools.photo": "Photo",

    // Tool Categories
    "tools.cat.diagnostic": "Diagnostic Système",
    "tools.cat.diagnosticDesc": "Analysez les performances de votre matériel",
    "tools.cat.disk": "Gestion Disque",
    "tools.cat.diskDesc": "Partitionnement et récupération de données",
    "tools.cat.network": "Réseau",
    "tools.cat.networkDesc": "Outils de diagnostic et monitoring réseau",
    "tools.cat.optimization": "Optimisation",
    "tools.cat.optimizationDesc": "Boostez les performances de votre PC",
    "tools.cat.passwords": "Mots de passe",
    "tools.cat.passwordsDesc": "Gestionnaires et générateurs sécurisés",
    "tools.cat.design": "Design",
    "tools.cat.designDesc": "Outils de capture et d'édition rapide",

    // CTA
    "cta.title": "Prêt à télécharger ?",
    "cta.description": "Rejoignez des milliers d'utilisateurs qui font confiance à Lekajio Software pour leurs logiciels et outils numériques.",
    "cta.button": "Commencer maintenant",

    // Card
    "card.download": "Télécharger",
    "card.downloads": "téléchargements",

    // Footer
    "footer.description": "Votre destination pour les meilleurs logiciels, VPN et outils numériques. Téléchargez en toute sécurité et restez à jour.",
    "footer.navigation": "Navigation",
    "footer.categories": "Catégories",
    "footer.contact": "Contact",
    "footer.antivirus": "Antivirus",
    "footer.vpnPremium": "VPN Premium",
    "footer.videoEditors": "Éditeurs Vidéo",
    "footer.systemTools": "Outils Système",
    "footer.browsers": "Navigateurs",
    "footer.office": "Bureautique",
    "footer.rights": "Tous droits réservés.",
    "footer.privacy": "Politique de confidentialité",
    "footer.terms": "Conditions d'utilisation",
    "footer.legal": "Mentions légales",

    // 404
    "notfound.title": "Page non trouvée",
    "notfound.description": "La page que vous recherchez n'existe pas ou a été déplacée.",
    "notfound.back": "Retour à l'accueil",
  },

  en: {
    "nav.home": "Home",
    "nav.vpn": "VPN",
    "nav.software": "Software",
    "nav.tools": "Tools",
    "nav.ai": "AI",
    "nav.download": "Download",
    "hero.badge": "New: Daily updates",
    "hero.title1": "Your favorite software",
    "hero.title2": "in one click",
    "hero.titleHighlight": "favorite",
    "hero.description": "Discover and download the best VPNs, software and digital tools. Secure, fast and always up to date.",
    "hero.cta1": "Explore software",
    "hero.cta2": "View VPNs",
    "features.speed": "Fast Download",
    "features.speedDesc": "High-speed servers for instant downloads",
    "features.secure": "100% Secure",
    "features.secureDesc": "All files are verified and virus-free",
    "features.global": "Global Access",
    "features.globalDesc": "Available worldwide, 24/7",
    "stats.downloads": "Downloads",
    "stats.users": "Active users",
    "stats.secure": "Secure",
    "stats.rating": "Average rating",
    "vpn.badge": "Protection & Privacy",
    "vpn.title": "Premium VPN",
    "vpn.seeAll": "See all",
    "vpn.comingSoon": "More VPNs coming soon",
    "vpn.pageTitle": "The best VPNs for your security",
    "vpn.pageDesc": "Protect your online privacy with our selection of the most reliable and powerful VPNs on the market.",
    "vpn.allTitle": "All available VPNs",
    "vpn.allDesc": "Choose the VPN that suits your needs",
    "vpn.spaceLabel": "VPN Space",
    "vpn.spaceReady": "Ready for your content",
    "vpn.feat.encryption": "AES-256 Encryption",
    "vpn.feat.encryptionDesc": "Military-grade protection for all your data",
    "vpn.feat.servers": "Global Servers",
    "vpn.feat.serversDesc": "Access content from any country",
    "vpn.feat.speed": "Maximum Speed",
    "vpn.feat.speedDesc": "No slowdowns thanks to our optimized servers",
    "vpn.feat.logs": "Zero Logs",
    "vpn.feat.logsDesc": "Your online activity remains completely private",
    "vpn.feat.devices": "Multi-device",
    "vpn.feat.devicesDesc": "Protect all your devices simultaneously",
    "vpn.feat.killswitch": "Kill Switch",
    "vpn.feat.killswitchDesc": "Automatic protection in case of disconnection",
    "software.badge": "Applications & Programs",
    "software.title": "Popular Software",
    "software.pageTitle": "All software",
    "software.pageDesc": "Explore our complete collection of professional software, utilities and productivity tools.",
    "software.pageBadge": "Software Library",
    "software.search": "Search for software...",
    "software.found": "software found",
    "software.spaceLabel": "Software space",
    "software.spaceReady": "Ready for your content",
    "software.reserved": "Space reserved for your software",
    "cat.all": "All",
    "cat.system": "System",
    "cat.video": "Video",
    "cat.security": "Security",
    "cat.utility": "Utilities",
    "cat.office": "Office",
    "cat.media": "Multimedia",
    "videos.badge": "Tutorials & Guides",
    "videos.title": "Videos & Tutorials",
    "videos.spaceLabel": "Video space available",
    "tools.badge": "Utilities & Productivity",
    "tools.title": "Digital Tools",
    "tools.pageTitle": "Digital tools",
    "tools.pageDesc": "Essential tools to diagnose, optimize and manage your computer system.",
    "tools.allTitle": "Available tools",
    "tools.allDesc": "Download the tools you need",
    "tools.comingSoon": "Coming soon",
    "tools.spaceLabel": "Tool",
    "tools.spaceReady": "Space available",
    "tools.gallery": "Photo Gallery",
    "tools.galleryDesc": "Screenshots and tool previews",
    "tools.photo": "Photo",
    "tools.cat.diagnostic": "System Diagnostic",
    "tools.cat.diagnosticDesc": "Analyze your hardware performance",
    "tools.cat.disk": "Disk Management",
    "tools.cat.diskDesc": "Partitioning and data recovery",
    "tools.cat.network": "Network",
    "tools.cat.networkDesc": "Network diagnostic and monitoring tools",
    "tools.cat.optimization": "Optimization",
    "tools.cat.optimizationDesc": "Boost your PC performance",
    "tools.cat.passwords": "Passwords",
    "tools.cat.passwordsDesc": "Secure managers and generators",
    "tools.cat.design": "Design",
    "tools.cat.designDesc": "Capture and quick editing tools",
    "cta.title": "Ready to download?",
    "cta.description": "Join thousands of users who trust Lekajio Software for their software and digital tools.",
    "cta.button": "Get started now",
    "card.download": "Download",
    "card.downloads": "downloads",
    "footer.description": "Your destination for the best software, VPNs and digital tools. Download safely and stay up to date.",
    "footer.navigation": "Navigation",
    "footer.categories": "Categories",
    "footer.contact": "Contact",
    "footer.antivirus": "Antivirus",
    "footer.vpnPremium": "Premium VPN",
    "footer.videoEditors": "Video Editors",
    "footer.systemTools": "System Tools",
    "footer.browsers": "Browsers",
    "footer.office": "Office",
    "footer.rights": "All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Use",
    "footer.legal": "Legal Notice",
    "notfound.title": "Page not found",
    "notfound.description": "The page you are looking for does not exist or has been moved.",
    "notfound.back": "Back to home",
  },

  zh: {
    "nav.home": "首页",
    "nav.vpn": "VPN",
    "nav.software": "软件",
    "nav.tools": "工具",
    "nav.ai": "AI",
    "nav.download": "下载",
    "hero.badge": "新功能：每日更新",
    "hero.title1": "您喜爱的软件",
    "hero.title2": "一键获取",
    "hero.titleHighlight": "喜爱的",
    "hero.description": "发现并下载最好的VPN、软件和数字工具。安全、快速且始终保持最新。",
    "hero.cta1": "浏览软件",
    "hero.cta2": "查看VPN",
    "features.speed": "极速下载",
    "features.speedDesc": "高速服务器，即时下载",
    "features.secure": "100% 安全",
    "features.secureDesc": "所有文件均经过验证，无病毒",
    "features.global": "全球访问",
    "features.globalDesc": "全球可用，全天候服务",
    "stats.downloads": "下载量",
    "stats.users": "活跃用户",
    "stats.secure": "安全",
    "stats.rating": "平均评分",
    "vpn.badge": "保护与隐私",
    "vpn.title": "高级VPN",
    "vpn.seeAll": "查看全部",
    "vpn.comingSoon": "更多VPN即将推出",
    "vpn.pageTitle": "最佳VPN保护您的安全",
    "vpn.pageDesc": "使用我们精选的最可靠、最强大的VPN保护您的在线隐私。",
    "vpn.allTitle": "所有可用VPN",
    "vpn.allDesc": "选择适合您需求的VPN",
    "vpn.spaceLabel": "VPN空间",
    "vpn.spaceReady": "等待您的内容",
    "vpn.feat.encryption": "AES-256加密",
    "vpn.feat.encryptionDesc": "军事级别的数据保护",
    "vpn.feat.servers": "全球服务器",
    "vpn.feat.serversDesc": "访问任何国家的内容",
    "vpn.feat.speed": "最高速度",
    "vpn.feat.speedDesc": "优化服务器，无速度损失",
    "vpn.feat.logs": "零日志",
    "vpn.feat.logsDesc": "您的在线活动完全私密",
    "vpn.feat.devices": "多设备",
    "vpn.feat.devicesDesc": "同时保护所有设备",
    "vpn.feat.killswitch": "Kill Switch",
    "vpn.feat.killswitchDesc": "断开连接时自动保护",
    "software.badge": "应用与程序",
    "software.title": "热门软件",
    "software.pageTitle": "所有软件",
    "software.pageDesc": "浏览我们完整的专业软件、实用工具和生产力工具集合。",
    "software.pageBadge": "软件库",
    "software.search": "搜索软件...",
    "software.found": "个软件",
    "software.spaceLabel": "软件空间",
    "software.spaceReady": "等待您的内容",
    "software.reserved": "为您的软件预留的空间",
    "cat.all": "全部",
    "cat.system": "系统",
    "cat.video": "视频",
    "cat.security": "安全",
    "cat.utility": "实用工具",
    "cat.office": "办公",
    "cat.media": "多媒体",
    "videos.badge": "教程与指南",
    "videos.title": "视频与教程",
    "videos.spaceLabel": "视频空间可用",
    "tools.badge": "实用工具与生产力",
    "tools.title": "数字工具",
    "tools.pageTitle": "数字工具",
    "tools.pageDesc": "诊断、优化和管理计算机系统的必备工具。",
    "tools.allTitle": "可用工具",
    "tools.allDesc": "下载您需要的工具",
    "tools.comingSoon": "即将推出",
    "tools.spaceLabel": "工具",
    "tools.spaceReady": "空间可用",
    "tools.gallery": "图片库",
    "tools.galleryDesc": "截图和工具预览",
    "tools.photo": "图片",
    "tools.cat.diagnostic": "系统诊断",
    "tools.cat.diagnosticDesc": "分析硬件性能",
    "tools.cat.disk": "磁盘管理",
    "tools.cat.diskDesc": "分区和数据恢复",
    "tools.cat.network": "网络",
    "tools.cat.networkDesc": "网络诊断和监控工具",
    "tools.cat.optimization": "优化",
    "tools.cat.optimizationDesc": "提升PC性能",
    "tools.cat.passwords": "密码",
    "tools.cat.passwordsDesc": "安全管理器和生成器",
    "tools.cat.design": "设计",
    "tools.cat.designDesc": "截图和快速编辑工具",
    "cta.title": "准备好下载了吗？",
    "cta.description": "加入数千名信任Lekajio Software的用户，获取软件和数字工具。",
    "cta.button": "立即开始",
    "card.download": "下载",
    "card.downloads": "次下载",
    "footer.description": "您获取最佳软件、VPN和数字工具的目的地。安全下载，保持更新。",
    "footer.navigation": "导航",
    "footer.categories": "分类",
    "footer.contact": "联系我们",
    "footer.antivirus": "杀毒软件",
    "footer.vpnPremium": "高级VPN",
    "footer.videoEditors": "视频编辑器",
    "footer.systemTools": "系统工具",
    "footer.browsers": "浏览器",
    "footer.office": "办公软件",
    "footer.rights": "版权所有。",
    "footer.privacy": "隐私政策",
    "footer.terms": "使用条款",
    "footer.legal": "法律声明",
    "notfound.title": "页面未找到",
    "notfound.description": "您查找的页面不存在或已被移动。",
    "notfound.back": "返回首页",
  },

  ar: {
    "nav.home": "الرئيسية",
    "nav.vpn": "VPN",
    "nav.software": "البرامج",
    "nav.tools": "الأدوات",
    "nav.ai": "AI",
    "nav.download": "تحميل",
    "hero.badge": "جديد: تحديثات يومية",
    "hero.title1": "برامجك المفضلة",
    "hero.title2": "بنقرة واحدة",
    "hero.titleHighlight": "المفضلة",
    "hero.description": "اكتشف وحمّل أفضل شبكات VPN والبرامج والأدوات الرقمية. آمن وسريع ومحدّث دائماً.",
    "hero.cta1": "استكشف البرامج",
    "hero.cta2": "عرض VPN",
    "features.speed": "تحميل سريع",
    "features.speedDesc": "خوادم عالية السرعة للتحميل الفوري",
    "features.secure": "آمن 100%",
    "features.secureDesc": "جميع الملفات تم التحقق منها وخالية من الفيروسات",
    "features.global": "وصول عالمي",
    "features.globalDesc": "متاح في جميع أنحاء العالم على مدار الساعة",
    "stats.downloads": "التحميلات",
    "stats.users": "المستخدمون النشطون",
    "stats.secure": "آمن",
    "stats.rating": "متوسط التقييم",
    "vpn.badge": "الحماية والخصوصية",
    "vpn.title": "VPN مميز",
    "vpn.seeAll": "عرض الكل",
    "vpn.comingSoon": "المزيد من VPN قريباً",
    "vpn.pageTitle": "أفضل VPN لأمانك",
    "vpn.pageDesc": "احمِ خصوصيتك على الإنترنت مع مجموعتنا من أكثر شبكات VPN موثوقية وقوة.",
    "vpn.allTitle": "جميع شبكات VPN المتاحة",
    "vpn.allDesc": "اختر VPN الذي يناسب احتياجاتك",
    "vpn.spaceLabel": "مساحة VPN",
    "vpn.spaceReady": "جاهز لمحتواك",
    "vpn.feat.encryption": "تشفير AES-256",
    "vpn.feat.encryptionDesc": "حماية بمستوى عسكري لجميع بياناتك",
    "vpn.feat.servers": "خوادم عالمية",
    "vpn.feat.serversDesc": "الوصول إلى المحتوى من أي بلد",
    "vpn.feat.speed": "أقصى سرعة",
    "vpn.feat.speedDesc": "بدون تباطؤ بفضل خوادمنا المحسّنة",
    "vpn.feat.logs": "بدون سجلات",
    "vpn.feat.logsDesc": "نشاطك على الإنترنت يبقى خاصاً تماماً",
    "vpn.feat.devices": "أجهزة متعددة",
    "vpn.feat.devicesDesc": "احمِ جميع أجهزتك في وقت واحد",
    "vpn.feat.killswitch": "Kill Switch",
    "vpn.feat.killswitchDesc": "حماية تلقائية عند انقطاع الاتصال",
    "software.badge": "التطبيقات والبرامج",
    "software.title": "البرامج الشائعة",
    "software.pageTitle": "جميع البرامج",
    "software.pageDesc": "استكشف مجموعتنا الكاملة من البرامج المهنية والأدوات المساعدة وأدوات الإنتاجية.",
    "software.pageBadge": "مكتبة البرامج",
    "software.search": "البحث عن برنامج...",
    "software.found": "برنامج تم العثور عليه",
    "software.spaceLabel": "مساحة برنامج",
    "software.spaceReady": "جاهز لمحتواك",
    "software.reserved": "مساحة محجوزة لبرامجك",
    "cat.all": "الكل",
    "cat.system": "النظام",
    "cat.video": "فيديو",
    "cat.security": "الأمان",
    "cat.utility": "أدوات مساعدة",
    "cat.office": "مكتبي",
    "cat.media": "وسائط متعددة",
    "videos.badge": "دروس وأدلة",
    "videos.title": "فيديوهات ودروس",
    "videos.spaceLabel": "مساحة فيديو متاحة",
    "tools.badge": "أدوات مساعدة وإنتاجية",
    "tools.title": "أدوات رقمية",
    "tools.pageTitle": "أدوات رقمية",
    "tools.pageDesc": "أدوات أساسية لتشخيص وتحسين وإدارة نظام الكمبيوتر الخاص بك.",
    "tools.allTitle": "الأدوات المتاحة",
    "tools.allDesc": "حمّل الأدوات التي تحتاجها",
    "tools.comingSoon": "قريباً",
    "tools.spaceLabel": "أداة",
    "tools.spaceReady": "مساحة متاحة",
    "tools.gallery": "معرض الصور",
    "tools.galleryDesc": "لقطات شاشة ومعاينات الأدوات",
    "tools.photo": "صورة",
    "tools.cat.diagnostic": "تشخيص النظام",
    "tools.cat.diagnosticDesc": "تحليل أداء الأجهزة",
    "tools.cat.disk": "إدارة الأقراص",
    "tools.cat.diskDesc": "التقسيم واستعادة البيانات",
    "tools.cat.network": "الشبكة",
    "tools.cat.networkDesc": "أدوات تشخيص ومراقبة الشبكة",
    "tools.cat.optimization": "التحسين",
    "tools.cat.optimizationDesc": "تعزيز أداء الكمبيوتر",
    "tools.cat.passwords": "كلمات المرور",
    "tools.cat.passwordsDesc": "مديرون ومولدون آمنون",
    "tools.cat.design": "التصميم",
    "tools.cat.designDesc": "أدوات الالتقاط والتحرير السريع",
    "cta.title": "مستعد للتحميل؟",
    "cta.description": "انضم إلى آلاف المستخدمين الذين يثقون في Lekajio Software لبرامجهم وأدواتهم الرقمية.",
    "cta.button": "ابدأ الآن",
    "card.download": "تحميل",
    "card.downloads": "تحميل",
    "footer.description": "وجهتك للحصول على أفضل البرامج وشبكات VPN والأدوات الرقمية. حمّل بأمان وابقَ محدّثاً.",
    "footer.navigation": "التنقل",
    "footer.categories": "الفئات",
    "footer.contact": "اتصل بنا",
    "footer.antivirus": "مضاد الفيروسات",
    "footer.vpnPremium": "VPN مميز",
    "footer.videoEditors": "محررات الفيديو",
    "footer.systemTools": "أدوات النظام",
    "footer.browsers": "المتصفحات",
    "footer.office": "مكتبي",
    "footer.rights": "جميع الحقوق محفوظة.",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الاستخدام",
    "footer.legal": "إشعار قانوني",
    "notfound.title": "الصفحة غير موجودة",
    "notfound.description": "الصفحة التي تبحث عنها غير موجودة أو تم نقلها.",
    "notfound.back": "العودة للرئيسية",
  },

  es: {
    "nav.home": "Inicio",
    "nav.vpn": "VPN",
    "nav.software": "Software",
    "nav.tools": "Herramientas",
    "nav.ai": "IA",
    "nav.download": "Descargar",
    "hero.badge": "Nuevo: Actualizaciones diarias",
    "hero.title1": "Tu software favorito",
    "hero.title2": "en un clic",
    "hero.titleHighlight": "favorito",
    "hero.description": "Descubre y descarga los mejores VPN, software y herramientas digitales. Seguro, rápido y siempre actualizado.",
    "hero.cta1": "Explorar software",
    "hero.cta2": "Ver VPNs",
    "features.speed": "Descarga Rápida",
    "features.speedDesc": "Servidores de alta velocidad para descargas instantáneas",
    "features.secure": "100% Seguro",
    "features.secureDesc": "Todos los archivos están verificados y libres de virus",
    "features.global": "Acceso Global",
    "features.globalDesc": "Disponible en todo el mundo, 24/7",
    "stats.downloads": "Descargas",
    "stats.users": "Usuarios activos",
    "stats.secure": "Seguro",
    "stats.rating": "Calificación promedio",
    "vpn.badge": "Protección y Privacidad",
    "vpn.title": "VPN Premium",
    "vpn.seeAll": "Ver todo",
    "vpn.comingSoon": "Más VPNs próximamente",
    "vpn.pageTitle": "Los mejores VPN para tu seguridad",
    "vpn.pageDesc": "Protege tu privacidad en línea con nuestra selección de los VPN más confiables y potentes del mercado.",
    "vpn.allTitle": "Todos los VPN disponibles",
    "vpn.allDesc": "Elige el VPN que se adapte a tus necesidades",
    "vpn.spaceLabel": "Espacio VPN",
    "vpn.spaceReady": "Listo para tu contenido",
    "vpn.feat.encryption": "Cifrado AES-256",
    "vpn.feat.encryptionDesc": "Protección de grado militar para todos tus datos",
    "vpn.feat.servers": "Servidores Globales",
    "vpn.feat.serversDesc": "Accede a contenido de cualquier país",
    "vpn.feat.speed": "Velocidad Máxima",
    "vpn.feat.speedDesc": "Sin ralentizaciones gracias a nuestros servidores optimizados",
    "vpn.feat.logs": "Cero Registros",
    "vpn.feat.logsDesc": "Tu actividad en línea permanece completamente privada",
    "vpn.feat.devices": "Multi-dispositivo",
    "vpn.feat.devicesDesc": "Protege todos tus dispositivos simultáneamente",
    "vpn.feat.killswitch": "Kill Switch",
    "vpn.feat.killswitchDesc": "Protección automática en caso de desconexión",
    "software.badge": "Aplicaciones y Programas",
    "software.title": "Software Popular",
    "software.pageTitle": "Todo el software",
    "software.pageDesc": "Explora nuestra colección completa de software profesional, utilidades y herramientas de productividad.",
    "software.pageBadge": "Biblioteca de software",
    "software.search": "Buscar software...",
    "software.found": "software encontrado(s)",
    "software.spaceLabel": "Espacio de software",
    "software.spaceReady": "Listo para tu contenido",
    "software.reserved": "Espacio reservado para tu software",
    "cat.all": "Todos",
    "cat.system": "Sistema",
    "cat.video": "Vídeo",
    "cat.security": "Seguridad",
    "cat.utility": "Utilidades",
    "cat.office": "Oficina",
    "cat.media": "Multimedia",
    "videos.badge": "Tutoriales y Guías",
    "videos.title": "Vídeos y Tutoriales",
    "videos.spaceLabel": "Espacio de vídeo disponible",
    "tools.badge": "Utilidades y Productividad",
    "tools.title": "Herramientas Digitales",
    "tools.pageTitle": "Herramientas digitales",
    "tools.pageDesc": "Herramientas esenciales para diagnosticar, optimizar y gestionar tu sistema informático.",
    "tools.allTitle": "Herramientas disponibles",
    "tools.allDesc": "Descarga las herramientas que necesitas",
    "tools.comingSoon": "Próximamente",
    "tools.spaceLabel": "Herramienta",
    "tools.spaceReady": "Espacio disponible",
    "tools.gallery": "Galería de Fotos",
    "tools.galleryDesc": "Capturas de pantalla y vistas previas",
    "tools.photo": "Foto",
    "tools.cat.diagnostic": "Diagnóstico del Sistema",
    "tools.cat.diagnosticDesc": "Analiza el rendimiento de tu hardware",
    "tools.cat.disk": "Gestión de Disco",
    "tools.cat.diskDesc": "Particionamiento y recuperación de datos",
    "tools.cat.network": "Red",
    "tools.cat.networkDesc": "Herramientas de diagnóstico y monitoreo de red",
    "tools.cat.optimization": "Optimización",
    "tools.cat.optimizationDesc": "Mejora el rendimiento de tu PC",
    "tools.cat.passwords": "Contraseñas",
    "tools.cat.passwordsDesc": "Gestores y generadores seguros",
    "tools.cat.design": "Diseño",
    "tools.cat.designDesc": "Herramientas de captura y edición rápida",
    "cta.title": "¿Listo para descargar?",
    "cta.description": "Únete a miles de usuarios que confían en Lekajio Software para su software y herramientas digitales.",
    "cta.button": "Comienza ahora",
    "card.download": "Descargar",
    "card.downloads": "descargas",
    "footer.description": "Tu destino para el mejor software, VPNs y herramientas digitales. Descarga de forma segura y mantente actualizado.",
    "footer.navigation": "Navegación",
    "footer.categories": "Categorías",
    "footer.contact": "Contacto",
    "footer.antivirus": "Antivirus",
    "footer.vpnPremium": "VPN Premium",
    "footer.videoEditors": "Editores de Vídeo",
    "footer.systemTools": "Herramientas del Sistema",
    "footer.browsers": "Navegadores",
    "footer.office": "Oficina",
    "footer.rights": "Todos los derechos reservados.",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos de Uso",
    "footer.legal": "Aviso Legal",
    "notfound.title": "Página no encontrada",
    "notfound.description": "La página que buscas no existe o ha sido movida.",
    "notfound.back": "Volver al inicio",
  },

  pt: {
    "nav.home": "Início",
    "nav.vpn": "VPN",
    "nav.software": "Software",
    "nav.tools": "Ferramentas",
    "nav.ai": "IA",
    "nav.download": "Baixar",
    "hero.badge": "Novo: Atualizações diárias",
    "hero.title1": "Seus softwares favoritos",
    "hero.title2": "em um clique",
    "hero.titleHighlight": "favoritos",
    "hero.description": "Descubra e baixe os melhores VPNs, softwares e ferramentas digitais. Seguro, rápido e sempre atualizado.",
    "hero.cta1": "Explorar softwares",
    "hero.cta2": "Ver VPNs",
    "features.speed": "Download Rápido",
    "features.speedDesc": "Servidores de alta velocidade para downloads instantâneos",
    "features.secure": "100% Seguro",
    "features.secureDesc": "Todos os arquivos são verificados e livres de vírus",
    "features.global": "Acesso Global",
    "features.globalDesc": "Disponível em todo o mundo, 24/7",
    "stats.downloads": "Downloads",
    "stats.users": "Usuários ativos",
    "stats.secure": "Seguro",
    "stats.rating": "Avaliação média",
    "vpn.badge": "Proteção e Privacidade",
    "vpn.title": "VPN Premium",
    "vpn.seeAll": "Ver tudo",
    "vpn.comingSoon": "Mais VPNs em breve",
    "vpn.pageTitle": "Os melhores VPNs para sua segurança",
    "vpn.pageDesc": "Proteja sua privacidade online com nossa seleção dos VPNs mais confiáveis e poderosos do mercado.",
    "vpn.allTitle": "Todos os VPNs disponíveis",
    "vpn.allDesc": "Escolha o VPN que atende às suas necessidades",
    "vpn.spaceLabel": "Espaço VPN",
    "vpn.spaceReady": "Pronto para seu conteúdo",
    "vpn.feat.encryption": "Criptografia AES-256",
    "vpn.feat.encryptionDesc": "Proteção de nível militar para todos os seus dados",
    "vpn.feat.servers": "Servidores Globais",
    "vpn.feat.serversDesc": "Acesse conteúdo de qualquer país",
    "vpn.feat.speed": "Velocidade Máxima",
    "vpn.feat.speedDesc": "Sem lentidão graças aos nossos servidores otimizados",
    "vpn.feat.logs": "Zero Logs",
    "vpn.feat.logsDesc": "Sua atividade online permanece completamente privada",
    "vpn.feat.devices": "Multi-dispositivos",
    "vpn.feat.devicesDesc": "Proteja todos os seus dispositivos simultaneamente",
    "vpn.feat.killswitch": "Kill Switch",
    "vpn.feat.killswitchDesc": "Proteção automática em caso de desconexão",
    "software.badge": "Aplicativos e Programas",
    "software.title": "Softwares Populares",
    "software.pageTitle": "Todos os softwares",
    "software.pageDesc": "Explore nossa coleção completa de softwares profissionais, utilitários e ferramentas de produtividade.",
    "software.pageBadge": "Biblioteca de softwares",
    "software.search": "Pesquisar software...",
    "software.found": "software(s) encontrado(s)",
    "software.spaceLabel": "Espaço de software",
    "software.spaceReady": "Pronto para seu conteúdo",
    "software.reserved": "Espaço reservado para seus softwares",
    "cat.all": "Todos",
    "cat.system": "Sistema",
    "cat.video": "Vídeo",
    "cat.security": "Segurança",
    "cat.utility": "Utilitários",
    "cat.office": "Escritório",
    "cat.media": "Multimídia",
    "videos.badge": "Tutoriais e Guias",
    "videos.title": "Vídeos e Tutoriais",
    "videos.spaceLabel": "Espaço de vídeo disponível",
    "tools.badge": "Utilitários e Produtividade",
    "tools.title": "Ferramentas Digitais",
    "tools.pageTitle": "Ferramentas digitais",
    "tools.pageDesc": "Ferramentas essenciais para diagnosticar, otimizar e gerenciar seu sistema de computador.",
    "tools.allTitle": "Ferramentas disponíveis",
    "tools.allDesc": "Baixe as ferramentas que você precisa",
    "tools.comingSoon": "Em breve",
    "tools.spaceLabel": "Ferramenta",
    "tools.spaceReady": "Espaço disponível",
    "tools.gallery": "Galeria de Fotos",
    "tools.galleryDesc": "Capturas de tela e prévias das ferramentas",
    "tools.photo": "Foto",
    "tools.cat.diagnostic": "Diagnóstico do Sistema",
    "tools.cat.diagnosticDesc": "Analise o desempenho do seu hardware",
    "tools.cat.disk": "Gerenciamento de Disco",
    "tools.cat.diskDesc": "Particionamento e recuperação de dados",
    "tools.cat.network": "Rede",
    "tools.cat.networkDesc": "Ferramentas de diagnóstico e monitoramento de rede",
    "tools.cat.optimization": "Otimização",
    "tools.cat.optimizationDesc": "Melhore o desempenho do seu PC",
    "tools.cat.passwords": "Senhas",
    "tools.cat.passwordsDesc": "Gerenciadores e geradores seguros",
    "tools.cat.design": "Design",
    "tools.cat.designDesc": "Ferramentas de captura e edição rápida",
    "cta.title": "Pronto para baixar?",
    "cta.description": "Junte-se a milhares de usuários que confiam no Lekajio Software para seus softwares e ferramentas digitais.",
    "cta.button": "Comece agora",
    "card.download": "Baixar",
    "card.downloads": "downloads",
    "footer.description": "Seu destino para os melhores softwares, VPNs e ferramentas digitais. Baixe com segurança e mantenha-se atualizado.",
    "footer.navigation": "Navegação",
    "footer.categories": "Categorias",
    "footer.contact": "Contato",
    "footer.antivirus": "Antivírus",
    "footer.vpnPremium": "VPN Premium",
    "footer.videoEditors": "Editores de Vídeo",
    "footer.systemTools": "Ferramentas do Sistema",
    "footer.browsers": "Navegadores",
    "footer.office": "Escritório",
    "footer.rights": "Todos os direitos reservados.",
    "footer.privacy": "Política de Privacidade",
    "footer.terms": "Termos de Uso",
    "footer.legal": "Aviso Legal",
    "notfound.title": "Página não encontrada",
    "notfound.description": "A página que você procura não existe ou foi movida.",
    "notfound.back": "Voltar ao início",
  },

  ja: {
    "nav.home": "ホーム",
    "nav.vpn": "VPN",
    "nav.software": "ソフトウェア",
    "nav.tools": "ツール",
    "nav.ai": "AI",
    "nav.download": "ダウンロード",
    "hero.badge": "新機能：毎日更新",
    "hero.title1": "お気に入りのソフトウェアを",
    "hero.title2": "ワンクリックで",
    "hero.titleHighlight": "お気に入り",
    "hero.description": "最高のVPN、ソフトウェア、デジタルツールを発見してダウンロード。安全、高速、常に最新。",
    "hero.cta1": "ソフトウェアを探す",
    "hero.cta2": "VPNを見る",
    "features.speed": "高速ダウンロード",
    "features.speedDesc": "高速サーバーで即時ダウンロード",
    "features.secure": "100% 安全",
    "features.secureDesc": "すべてのファイルは検証済みでウイルスフリー",
    "features.global": "グローバルアクセス",
    "features.globalDesc": "世界中で24時間利用可能",
    "stats.downloads": "ダウンロード数",
    "stats.users": "アクティブユーザー",
    "stats.secure": "安全",
    "stats.rating": "平均評価",
    "vpn.badge": "保護とプライバシー",
    "vpn.title": "プレミアムVPN",
    "vpn.seeAll": "すべて見る",
    "vpn.comingSoon": "さらに多くのVPNが近日公開",
    "vpn.pageTitle": "セキュリティのための最高のVPN",
    "vpn.pageDesc": "市場で最も信頼性が高く強力なVPNでオンラインプライバシーを保護しましょう。",
    "vpn.allTitle": "利用可能なすべてのVPN",
    "vpn.allDesc": "ニーズに合ったVPNを選択してください",
    "vpn.spaceLabel": "VPNスペース",
    "vpn.spaceReady": "コンテンツの準備完了",
    "vpn.feat.encryption": "AES-256暗号化",
    "vpn.feat.encryptionDesc": "すべてのデータに軍事レベルの保護",
    "vpn.feat.servers": "グローバルサーバー",
    "vpn.feat.serversDesc": "どの国のコンテンツにもアクセス",
    "vpn.feat.speed": "最高速度",
    "vpn.feat.speedDesc": "最適化されたサーバーで速度低下なし",
    "vpn.feat.logs": "ゼロログ",
    "vpn.feat.logsDesc": "オンライン活動は完全にプライベート",
    "vpn.feat.devices": "マルチデバイス",
    "vpn.feat.devicesDesc": "すべてのデバイスを同時に保護",
    "vpn.feat.killswitch": "Kill Switch",
    "vpn.feat.killswitchDesc": "切断時の自動保護",
    "software.badge": "アプリケーションとプログラム",
    "software.title": "人気ソフトウェア",
    "software.pageTitle": "すべてのソフトウェア",
    "software.pageDesc": "プロフェッショナルソフトウェア、ユーティリティ、生産性ツールの完全なコレクションを探索。",
    "software.pageBadge": "ソフトウェアライブラリ",
    "software.search": "ソフトウェアを検索...",
    "software.found": "件のソフトウェア",
    "software.spaceLabel": "ソフトウェアスペース",
    "software.spaceReady": "コンテンツの準備完了",
    "software.reserved": "ソフトウェア用の予約スペース",
    "cat.all": "すべて",
    "cat.system": "システム",
    "cat.video": "ビデオ",
    "cat.security": "セキュリティ",
    "cat.utility": "ユーティリティ",
    "cat.office": "オフィス",
    "cat.media": "マルチメディア",
    "videos.badge": "チュートリアルとガイド",
    "videos.title": "ビデオとチュートリアル",
    "videos.spaceLabel": "ビデオスペース利用可能",
    "tools.badge": "ユーティリティと生産性",
    "tools.title": "デジタルツール",
    "tools.pageTitle": "デジタルツール",
    "tools.pageDesc": "コンピュータシステムの診断、最適化、管理に必要なツール。",
    "tools.allTitle": "利用可能なツール",
    "tools.allDesc": "必要なツールをダウンロード",
    "tools.comingSoon": "近日公開",
    "tools.spaceLabel": "ツール",
    "tools.spaceReady": "スペース利用可能",
    "tools.gallery": "フォトギャラリー",
    "tools.galleryDesc": "スクリーンショットとツールプレビュー",
    "tools.photo": "写真",
    "tools.cat.diagnostic": "システム診断",
    "tools.cat.diagnosticDesc": "ハードウェアパフォーマンスを分析",
    "tools.cat.disk": "ディスク管理",
    "tools.cat.diskDesc": "パーティションとデータ復旧",
    "tools.cat.network": "ネットワーク",
    "tools.cat.networkDesc": "ネットワーク診断・監視ツール",
    "tools.cat.optimization": "最適化",
    "tools.cat.optimizationDesc": "PCパフォーマンスを向上",
    "tools.cat.passwords": "パスワード",
    "tools.cat.passwordsDesc": "安全なマネージャーとジェネレーター",
    "tools.cat.design": "デザイン",
    "tools.cat.designDesc": "キャプチャと簡易編集ツール",
    "cta.title": "ダウンロードの準備はできましたか？",
    "cta.description": "ソフトウェアとデジタルツールでLekajio Softwareを信頼する数千人のユーザーに参加しましょう。",
    "cta.button": "今すぐ始める",
    "card.download": "ダウンロード",
    "card.downloads": "ダウンロード",
    "footer.description": "最高のソフトウェア、VPN、デジタルツールの目的地。安全にダウンロードして最新の状態を維持。",
    "footer.navigation": "ナビゲーション",
    "footer.categories": "カテゴリー",
    "footer.contact": "お問い合わせ",
    "footer.antivirus": "アンチウイルス",
    "footer.vpnPremium": "プレミアムVPN",
    "footer.videoEditors": "ビデオエディター",
    "footer.systemTools": "システムツール",
    "footer.browsers": "ブラウザ",
    "footer.office": "オフィス",
    "footer.rights": "全著作権所有。",
    "footer.privacy": "プライバシーポリシー",
    "footer.terms": "利用規約",
    "footer.legal": "法的通知",
    "notfound.title": "ページが見つかりません",
    "notfound.description": "お探しのページは存在しないか、移動されました。",
    "notfound.back": "ホームに戻る",
  },
};

// ─── Provider ────────────────────────────────────────────────────

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("softwarehub-lang");
    if (saved && translations[saved as Language]) return saved as Language;
    return "fr";
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("softwarehub-lang", lang);
  }, []);

  const t = useCallback(
    (key: string): string => {
      return translations[language]?.[key] ?? translations.fr[key] ?? key;
    },
    [language]
  );

  const langInfo = languages.find((l) => l.code === language) ?? languages[0];

  useEffect(() => {
    document.documentElement.dir = langInfo.dir;
    document.documentElement.lang = language;
  }, [language, langInfo.dir]);

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        dir: langInfo.dir,
        languageInfo: langInfo,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}
